/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated.trips'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicActivitiesRouteImport } from './routes/_public.activities'
import { Route as PublicCitiesRouteImport } from './routes/_public.cities'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public.forgot-password'
import { Route as PublicResetPasswordRouteImport } from './routes/_public.reset-password'
import { Route as PublicSignInRouteImport } from './routes/_public.sign-in'
import { Route as PublicSignUpRouteImport } from './routes/_public.sign-up'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public.verify-email'
import { Route as AuthenticatedTripsNewRouteImport } from './routes/_authenticated.trips_.new'
import { Route as PublicActivitiesActivityIdRouteImport } from './routes/_public.activities_.$activityId'
import { Route as PublicCitiesCityIdRouteImport } from './routes/_public.cities_.$cityId'
import { Route as PublicShareTokenRouteImport } from './routes/_public.share.$token'
import { Route as PublicTripsTripIdRouteImport } from './routes/_public.trips.$tripId'
import { Route as AuthenticatedTripsTripIdManageRouteImport } from './routes/_authenticated.trips_.$tripId.manage'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicActivitiesRoute = PublicActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCitiesRoute = PublicCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTripsNewRoute = AuthenticatedTripsNewRouteImport.update({
  id: '/trips_/new',
  path: '/trips/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicActivitiesActivityIdRoute =
  PublicActivitiesActivityIdRouteImport.update({
    id: '/activities_/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicCitiesCityIdRoute = PublicCitiesCityIdRouteImport.update({
  id: '/cities_/$cityId',
  path: '/cities/$cityId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShareTokenRoute = PublicShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTripsTripIdRoute = PublicTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTripsTripIdManageRoute =
  AuthenticatedTripsTripIdManageRouteImport.update({
    id: '/trips_/$tripId/manage',
    path: '/trips/$tripId/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/activities': typeof PublicActivitiesRoute
  '/cities': typeof PublicCitiesRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/activities/$activityId': typeof PublicActivitiesActivityIdRoute
  '/cities/$cityId': typeof PublicCitiesCityIdRoute
  '/share/$token': typeof PublicShareTokenRoute
  '/trips/$tripId': typeof PublicTripsTripIdRoute
  '/trips/$tripId/manage': typeof AuthenticatedTripsTripIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/activities': typeof PublicActivitiesRoute
  '/cities': typeof PublicCitiesRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/activities/$activityId': typeof PublicActivitiesActivityIdRoute
  '/cities/$cityId': typeof PublicCitiesCityIdRoute
  '/share/$token': typeof PublicShareTokenRoute
  '/trips/$tripId': typeof PublicTripsTripIdRoute
  '/trips/$tripId/manage': typeof AuthenticatedTripsTripIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/_public/activities': typeof PublicActivitiesRoute
  '/_public/cities': typeof PublicCitiesRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/trips_/new': typeof AuthenticatedTripsNewRoute
  '/_public/activities_/$activityId': typeof PublicActivitiesActivityIdRoute
  '/_public/cities_/$cityId': typeof PublicCitiesCityIdRoute
  '/_public/share/$token': typeof PublicShareTokenRoute
  '/_public/trips/$tripId': typeof PublicTripsTripIdRoute
  '/_authenticated/trips_/$tripId/manage': typeof AuthenticatedTripsTripIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/trips'
    | '/activities'
    | '/cities'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/trips/new'
    | '/activities/$activityId'
    | '/cities/$cityId'
    | '/share/$token'
    | '/trips/$tripId'
    | '/trips/$tripId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/trips'
    | '/activities'
    | '/cities'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/trips/new'
    | '/activities/$activityId'
    | '/cities/$cityId'
    | '/share/$token'
    | '/trips/$tripId'
    | '/trips/$tripId/manage'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/trips'
    | '/_public/activities'
    | '/_public/cities'
    | '/_public/forgot-password'
    | '/_public/reset-password'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_public/verify-email'
    | '/_public/'
    | '/_authenticated/trips_/new'
    | '/_public/activities_/$activityId'
    | '/_public/cities_/$cityId'
    | '/_public/share/$token'
    | '/_public/trips/$tripId'
    | '/_authenticated/trips_/$tripId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/activities': {
      id: '/_public/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof PublicActivitiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cities': {
      id: '/_public/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof PublicCitiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/trips_/new': {
      id: '/_authenticated/trips_/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/activities_/$activityId': {
      id: '/_public/activities_/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof PublicActivitiesActivityIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cities_/$cityId': {
      id: '/_public/cities_/$cityId'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId'
      preLoaderRoute: typeof PublicCitiesCityIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/share/$token': {
      id: '/_public/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof PublicShareTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/trips/$tripId': {
      id: '/_public/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof PublicTripsTripIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/trips_/$tripId/manage': {
      id: '/_authenticated/trips_/$tripId/manage'
      path: '/trips/$tripId/manage'
      fullPath: '/trips/$tripId/manage'
      preLoaderRoute: typeof AuthenticatedTripsTripIdManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedTripsTripIdManageRoute: typeof AuthenticatedTripsTripIdManageRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedTripsTripIdManageRoute: AuthenticatedTripsTripIdManageRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicActivitiesRoute: typeof PublicActivitiesRoute
  PublicCitiesRoute: typeof PublicCitiesRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicActivitiesActivityIdRoute: typeof PublicActivitiesActivityIdRoute
  PublicCitiesCityIdRoute: typeof PublicCitiesCityIdRoute
  PublicShareTokenRoute: typeof PublicShareTokenRoute
  PublicTripsTripIdRoute: typeof PublicTripsTripIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicActivitiesRoute: PublicActivitiesRoute,
  PublicCitiesRoute: PublicCitiesRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicActivitiesActivityIdRoute: PublicActivitiesActivityIdRoute,
  PublicCitiesCityIdRoute: PublicCitiesCityIdRoute,
  PublicShareTokenRoute: PublicShareTokenRoute,
  PublicTripsTripIdRoute: PublicTripsTripIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
