/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as TripsNewBuildRouteImport } from './routes/trips.new.build'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewBuildRoute = TripsNewBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => TripsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/trips/new': typeof TripsNewRouteWithChildren
  '/trips/new/build': typeof TripsNewBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/trips/new': typeof TripsNewRouteWithChildren
  '/trips/new/build': typeof TripsNewBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/trips/new': typeof TripsNewRouteWithChildren
  '/trips/new/build': typeof TripsNewBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/trips/new' | '/trips/new/build'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/trips/new' | '/trips/new/build'
  id:
    '__root__' | '/' | '/login' | '/signup' | '/trips/new' | '/trips/new/build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TripsNewRoute: typeof TripsNewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new/build': {
      id: '/trips/new/build'
      path: '/build'
      fullPath: '/trips/new/build'
      preLoaderRoute: typeof TripsNewBuildRouteImport
      parentRoute: typeof TripsNewRoute
    }
  }
}

interface TripsNewRouteChildren {
  TripsNewBuildRoute: typeof TripsNewBuildRoute
}

const TripsNewRouteChildren: TripsNewRouteChildren = {
  TripsNewBuildRoute: TripsNewBuildRoute,
}

const TripsNewRouteWithChildren = TripsNewRoute._addFileChildren(
  TripsNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TripsNewRoute: TripsNewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
