import { BarChart3, CheckCircle2, Map, Users } from "lucide-react"

import { Card, CardContent } from "@/components/ui/card"
import { HeroSearch } from "@/features/home/HeroBanner"
import { HomeNavbar } from "@/features/home/HomeNavbar"

const metrics = [{ label: "Active travelers", value: "12,480", change: "+12.4%", icon: Users }, { label: "Trips planned", value: "3,842", change: "+8.1%", icon: Map }, { label: "Community posts", value: "1,204", change: "+16.8%", icon: BarChart3 }]

export function Admin() {
  return <main className="min-h-svh bg-[#f8f7f4] text-[#0f2744]"><HomeNavbar /><div className="border-b border-[#e6ebec] bg-white"><HeroSearch placeholder="Search admin records..." /></div><div className="mx-auto max-w-[1060px] px-5 pb-16 pt-8 sm:px-8 lg:pt-10"><header className="mb-7"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.18em] text-[#0d7a8a]">Workspace overview</p><h1 className="font-heading text-[38px] font-semibold leading-none">Admin</h1><p className="mt-2 text-sm text-[#526984]">A quiet view of the people and journeys shaping GlobeTrotter.</p></header><div className="grid gap-4 md:grid-cols-3">{metrics.map(({ label, value, change, icon: Icon }) => <Card key={label} className="rounded-xl border-[#e1e7eb] bg-white shadow-[0_2px_8px_rgba(15,39,68,.06)]"><CardContent className="p-5"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-lg bg-[#e8f3f4] text-[#0d7a8a]"><Icon className="size-4" aria-hidden="true" /></span><span className="text-[11px] font-semibold text-[#188260]">{change}</span></div><p className="mt-5 text-xs text-[#7890a3]">{label}</p><p className="mt-1 font-heading text-3xl font-semibold">{value}</p></CardContent></Card>)}</div><Card className="mt-5 rounded-xl border-[#e1e7eb] bg-white shadow-[0_2px_8px_rgba(15,39,68,.06)]"><CardContent className="p-6"><div className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#188260]" aria-hidden="true" /><h2 className="font-heading text-2xl font-semibold">Recent activity</h2></div><div className="mt-5 space-y-4 text-xs text-[#607991]"><p className="border-b border-[#edf0f1] pb-4"><strong className="text-[#0f2744]">Barcelona Summer Escape</strong> was added to the ongoing trips list.</p><p className="border-b border-[#edf0f1] pb-4"><strong className="text-[#0f2744]">Maya Chen</strong> shared a new community story.</p><p><strong className="text-[#0f2744]">Tokyo Autumn Adventure</strong> is ready for itinerary review.</p></div></CardContent></Card></div></main>
}
